name: biosimdb-interface CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install biosimdb-interface and its testing dependencies
        run: pip install -e .[testing]

      - name: Get latest biosim-schema release tag (or fail if none)
        id: schema-tag
        shell: bash
        run: |
          # Attempt to get the latest release tag. If no releases exist, this command will fail,
          # and the workflow will stop here, which is appropriate if release assets are mandatory.
          TAG=$(gh release view --repo CCPBioSim/biosim-schema --json tagName --template '{{.tagName}}')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download biosim-schema artifacts
        run: gh release download ${{ steps.schema-tag.outputs.tag }} --repo CCPBioSim/biosim-schema --pattern "biosim-schema-artifacts.tar.gz"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract biosim-schema artifacts
        shell: bash
        run: |
          mkdir -p biosim-schema
          tar -xzf biosim-schema-artifacts.tar.gz -C biosim-schema

      - name: Run test suite
        run: pytest --cov biosimdb_interface --cov-report term-missing --cov-append tests/
        env:
          WEBFORM_SCHEMA_PATH: ${{ github.workspace }}/biosim-schema/project/schema_webformfields.json
          ENGINE_MAPPING_SCHEMA_PATH: ${{ github.workspace }}/biosim-schema/project/schema_enginemappings.json
          BIOSIM_SCHEMA_PATH: ${{ github.workspace }}/biosim-schema/biosim_schema/schema/biosim_schema.yaml
          SECRET_KEY: "ci-testing-only-key"

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          fail-on-error: false

  coveralls-finish:
    name: Finish Coveralls
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
        fail-on-error: false

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up Python 3.14
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.14.0
      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[docs]
      - name: Build docs
        run: cd docs && make

  pre-commit:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up Python 3.14
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.14.0
      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[pre-commit]
      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
